# Generated by Django 3.2.12 on 2022-08-16 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='c', max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_pic', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=45)),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=45)),
                ('predict_pic', models.CharField(max_length=100)),
                ('count_result', models.IntegerField()),
                ('label', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='account',
            name='password_salt',
            field=models.CharField(max_length=100),
        ),
    ]
